// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PieShop.API.DbContexts;

#nullable disable

namespace PieShop.API.Migrations
{
    [DbContext(typeof(PieShopDbContext))]
    partial class PieShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PieShop.API.Entitites.Pie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("PieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70822596-265d-49e3-8ccc-cd996093e601"),
                            Description = "Our famous apple pies!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg",
                            InStock = true,
                            PieName = "Apple Pie",
                            Price = 15.949999999999999,
                            PurchasePrice = 9.5
                        },
                        new
                        {
                            Id = new Guid("11db10f5-c461-490f-a7a3-5ba5af3a58af"),
                            Description = "You'll love it!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/blueberrycheesecakesmall.jpg",
                            InStock = true,
                            PieName = "Blueberry cheese cake",
                            Price = 18.949999999999999,
                            PurchasePrice = 11.949999999999999
                        },
                        new
                        {
                            Id = new Guid("0ac44f1c-84fb-4bcc-8e1f-49fcc8f2a17c"),
                            Description = "Plain cheese cake. Plain pleasure.",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cheesecakesmall.jpg",
                            InStock = true,
                            PieName = "Cheese cake",
                            Price = 12.949999999999999,
                            PurchasePrice = 7.5
                        },
                        new
                        {
                            Id = new Guid("71a9453f-7a6b-40ac-9d66-e659296ef128"),
                            Description = "A summer classic!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg",
                            InStock = true,
                            PieName = "Cherry pie",
                            Price = 15.949999999999999,
                            PurchasePrice = 9.5
                        },
                        new
                        {
                            Id = new Guid("27629373-72aa-40cc-9819-993440356585"),
                            Description = "Happy holidays with this pie!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg",
                            InStock = true,
                            PieName = "Christmas apple pie",
                            Price = 12.949999999999999,
                            PurchasePrice = 6.5
                        },
                        new
                        {
                            Id = new Guid("27629374-72aa-40cc-9819-993440356585"),
                            Description = "Sweet as peach!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg",
                            InStock = true,
                            PieName = "Peach pie",
                            Price = 12.949999999999999,
                            PurchasePrice = 6.5
                        },
                        new
                        {
                            Id = new Guid("faa549e9-f940-4a2d-b5fe-93d3a9edbce7"),
                            Description = "Our Halloween favorite",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg",
                            InStock = true,
                            PieName = "Pumpkin Pie",
                            Price = 12.949999999999999,
                            PurchasePrice = 6.5
                        },
                        new
                        {
                            Id = new Guid("caa2a5d5-99d4-423c-b1f3-1b0e48c483c3"),
                            Description = "A Christmas favorite",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg",
                            InStock = true,
                            PieName = "Cranberry pie",
                            Price = 12.949999999999999,
                            PurchasePrice = 6.5
                        },
                        new
                        {
                            Id = new Guid("27529374-72aa-40cc-9819-993440356582"),
                            Description = "My God, so sweet!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg",
                            InStock = true,
                            PieName = "Rhubarb pie",
                            Price = 12.949999999999999,
                            PurchasePrice = 6.5
                        },
                        new
                        {
                            Id = new Guid("c956b141-3fc7-4176-9fed-a726a9eb47fa"),
                            Description = "You'll love it!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg",
                            InStock = true,
                            PieName = "Strawberry cheese cake",
                            Price = 12.949999999999999,
                            PurchasePrice = 6.5
                        },
                        new
                        {
                            Id = new Guid("8c9ac766-bc2f-40f0-acb1-b0ad6157c07b"),
                            Description = "Our delicious strawberry pie!",
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg",
                            InStock = true,
                            PieName = "Strawberry pie",
                            Price = 12.949999999999999,
                            PurchasePrice = 7.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
